### ISSUE TITLE
Execution of EasyCGTree.pl aborted due to compilation errors

### ISSUE THREAD

**Issue by Krasnopeev** [zdf1987/EasyCGTree4#3]
Hi!
I tried to run your app and faced with error. 
I'm absolutely noob in perl, what's wrong? 

I working in linux (Kubuntu 23.04).

Here I tried to run on test data you provided in `ExampleData.zip`
` perl EasyCGTree.pl -proteome Proteome`

```
anri@anriPC:~/EasyCGTree4/EasyCGTree4.1-Linux$ perl EasyCGTree.pl -proteome Proteome
Useless use of a constant ("-i") in void context at EasyCGTree.pl line 777.
Useless use of string in void context at EasyCGTree.pl line 777.
Useless use of a constant ("-o") in void context at EasyCGTree.pl line 777.
Useless use of string in void context at EasyCGTree.pl line 777.
Useless use of a constant ("--outfmt=fasta") in void context at EasyCGTree.pl line 777.
Useless use of a constant ("--output-order=tree-order") in void context at EasyCGTree.pl line 777.
Useless use of string in void context at EasyCGTree.pl line 777.
Useless use of a constant ("-v") in void context at EasyCGTree.pl line 777.
Useless use of a constant ("--force") in void context at EasyCGTree.pl line 777.
Global symbol "$astral" requires explicit package name (did you forget to declare "my $astral"?) at EasyCGTree.pl line 834.
Global symbol "$astral" requires explicit package name (did you forget to declare "my $astral"?) at EasyCGTree.pl line 1151.
Execution of EasyCGTree.pl aborted due to compilation errors.

```
command `perl EasyCGTree.pl -help` return the same error log.
I also applied `chmod +x` command for `bin` folder as well.

P.S. Update:
I add string `my $astral = "";` at the start of file ` EasyCGTree.pl` and it seem to work, but another errow occured 

````
 anri@anriPC:~/EasyCGTree4/EasyCGTree4.1$ perl EasyCGTree.pl -proteome Proteome -thread 12
Useless use of a constant ("-i") in void context at EasyCGTree.pl line 778.
Useless use of string in void context at EasyCGTree.pl line 778.
Useless use of a constant ("-o") in void context at EasyCGTree.pl line 778.
Useless use of string in void context at EasyCGTree.pl line 778.
Useless use of a constant ("--outfmt=fasta") in void context at EasyCGTree.pl line 778.
Useless use of a constant ("--output-order=tree-order") in void context at EasyCGTree.pl line 778.
Useless use of string in void context at EasyCGTree.pl line 778.
Useless use of a constant ("-v") in void context at EasyCGTree.pl line 778.
Useless use of a constant ("--force") in void context at EasyCGTree.pl line 778.

##############################
Reading command line... checking options and input data...


Totally, 31 files have been renamed successfully!


###############Starting Informations ###############

====== EasyCGTree ======
        Version 4.1
by Dao-Feng Zhang (Hohai University, China)

#########################

Options: 
-proteome Proteome
-task all
-tree sm
-tree_app fasttree
-trim strict
-hmm bac120
-thread 12
-evalue 1e-10
-gene_cutoff 0.8
-genome_cutoff 0.8

#########################

Job Started at: 15:54:10,2023-11-23

*****The user ordered a complete analysis (-task all) of the pipeline!

############### Task 1: HMM search ###############
#============= Step 1: HMM search ==============# 
Step 1: Do HMM search against 33 files in directory 'Proteome': 

        Searching against './Proteome/GCF-016757275.1.fas': 11/33 (33.33%).           
Error: Sequence file ./Proteome/. is empty or misformatted

Step 1: Can't execute 'hmmsearch': 
Please make sure: 'hmmsearch' is present in directory 'bin'.
````

**Comment by zdf1987** [comment]
Dear Andrew，
Thank you for your Email. Please fine a updated script "EasyCGTree.pl" in the attachment. If you can run it successfully, please tell. I will replace it in the GitHub.
Best regards,



Dao-Feng Zhang, Ph. D. 
Institute of Marine Biology, College of Oceanography, Hohai University
No.1 Xikang Road, Nanjing 210098, P.R. China.
E-mail: @hhu.edu.cn & ***@***.***
Tel：+86 15221393487

 
﻿﻿﻿﻿






---- Replied Message ----
| From | Andrew ***@***.***> |
| Date | 11/23/2023 16:07 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [zdf1987/EasyCGTree4] Execution of EasyCGTree.pl aborted due to compilation errors (Issue #3) |

Hi!
I tried to run your app and faced with error.
I'm absolutely noob in perl, what's wrong?

I working in linux (Kubuntu 23.04).

Here I tried to run on test data you provided in ExampleData.zip
perl EasyCGTree.pl -proteome Proteome

***@***.***:~/EasyCGTree4/EasyCGTree4.1-Linux$ perl EasyCGTree.pl -proteome Proteome
Useless use of a constant ("-i") in void context at EasyCGTree.pl line 777.
Useless use of string in void context at EasyCGTree.pl line 777.
Useless use of a constant ("-o") in void context at EasyCGTree.pl line 777.
Useless use of string in void context at EasyCGTree.pl line 777.
Useless use of a constant ("--outfmt=fasta") in void context at EasyCGTree.pl line 777.
Useless use of a constant ("--output-order=tree-order") in void context at EasyCGTree.pl line 777.
Useless use of string in void context at EasyCGTree.pl line 777.
Useless use of a constant ("-v") in void context at EasyCGTree.pl line 777.
Useless use of a constant ("--force") in void context at EasyCGTree.pl line 777.
Global symbol "$astral" requires explicit package name (did you forget to declare "my $astral"?) at EasyCGTree.pl line 834.
Global symbol "$astral" requires explicit package name (did you forget to declare "my $astral"?) at EasyCGTree.pl line 1151.
Execution of EasyCGTree.pl aborted due to compilation errors.



command perl EasyCGTree.pl -help return the same error log.
I also applied chmod +x command for bin folder as well.

P.S. Update:
I add string my $astral = ""; at the start of file EasyCGTree.pl and it seem to work, but another errow occured

 ***@***.***:~/EasyCGTree4/EasyCGTree4.1$ perl EasyCGTree.pl -proteome Proteome -thread 12
Useless use of a constant ("-i") in void context at EasyCGTree.pl line 778.
Useless use of string in void context at EasyCGTree.pl line 778.
Useless use of a constant ("-o") in void context at EasyCGTree.pl line 778.
Useless use of string in void context at EasyCGTree.pl line 778.
Useless use of a constant ("--outfmt=fasta") in void context at EasyCGTree.pl line 778.
Useless use of a constant ("--output-order=tree-order") in void context at EasyCGTree.pl line 778.
Useless use of string in void context at EasyCGTree.pl line 778.
Useless use of a constant ("-v") in void context at EasyCGTree.pl line 778.
Useless use of a constant ("--force") in void context at EasyCGTree.pl line 778.

##############################
Reading command line... checking options and input data...


Totally, 31 files have been renamed successfully!


###############Starting Informations ###############

====== EasyCGTree ======
        Version 4.1
by Dao-Feng Zhang (Hohai University, China)

#########################

Options: 
-proteome Proteome
-task all
-tree sm
-tree_app fasttree
-trim strict
-hmm bac120
-thread 12
-evalue 1e-10
-gene_cutoff 0.8
-genome_cutoff 0.8

#########################

Job Started at: 15:54:10,2023-11-23

*****The user ordered a complete analysis (-task all) of the pipeline!

############### Task 1: HMM search ###############
#============= Step 1: HMM search ==============# 
Step 1: Do HMM search against 33 files in directory 'Proteome': 

        Searching against './Proteome/GCF-016757275.1.fas': 11/33 (33.33%).           
Error: Sequence file ./Proteome/. is empty or misformatted

Step 1: Can't execute 'hmmsearch': 
Please make sure: 'hmmsearch' is present in directory 'bin'.

**Comment by zdf1987** [comment]
I have uploaded a updated version for Linux. Please try again. Further comments are welcome.

**Comment by Krasnopeev** [comment]
Thaks for update! @zdf1987

I tried again with uptaded script and here is another error occured.

```
#============= Step 8: Phylogeny Inference ==============#

Infering phylogeny of the supermatrices approach......

sh: 1: ./bin/FastTree.exe: not found

The supermatrix tree has been written successfully in 'Proteome/.supermatrix.fasttree.tree'.


############### Ending Information ###############

Job was finished at: 14:44:11,2023-11-24.
Running time: 0 d 0 h 3 min 2 sec.

```
File `.bac120.supermatrix.fasttree.tree` is empty and has 0kb size.

But there is nothing abount this error in `*.log` file.
Attached log file also.
[bac120.sm.fasttree_2023-11-24-14-41.log](https://github.com/zdf1987/EasyCGTree4/files/13455892/bac120.sm.fasttree_2023-11-24-14-41.log)

**Comment by Krasnopeev** [comment]
update:
I replaced new `tree_app-options.txt` with previous version and it seems to help.
here is one line difference between them
`FastTree Command-line=FastTreeMP`
and
`FastTree Command-line=FastTree.exe`

And another tip:
Output files `*.tree`,  `*.log` and `*.concatenation.fas` are hidden on linux because when script writes its to disk it add dot `.` at start in name of each file. For example output files are: 
`.bac120.supermatrix.fasttree.tree`, `.bac120.sm.fasttree_2023-11-24-15-5.log`, `.bac120.concatenation.fas` are hiiden in filemanager.

After all script runs properly.

**Comment by zdf1987** [comment]
Thank you for informing me that. I and many users mainly focus on the Windows version. You are the first of reporting bugs of the Linux version. I really appreciate it.
Best wishes,


﻿﻿﻿﻿

Dao-Feng Zhang, Ph. D. 
Institute of Marine Biology, College of Oceanography, Hohai University
No.1 Xikang Road, Nanjing 210098, P.R. China.
E-mail: @hhu.edu.cn & ***@***.***
Tel：+86 15221393487

 
﻿﻿﻿﻿






---- Replied Message ----
| From | Andrew ***@***.***> |
| Date | 11/24/2023 15:20 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [zdf1987/EasyCGTree4] Execution of EasyCGTree.pl aborted due to compilation errors (Issue #3) |

update:
I replaced new tree_app-options.txt with previous version and it seems to help.
here is one line difference between them
FastTree Command-line=FastTreeMP
and
FastTree Command-line=FastTree.exe

And another tip:
Output files *.tree, *.log and *.concatenation.fas are hidden on linux because when script writes its to disk it add dot . at start in name of each file. For example output files are:
.bac120.supermatrix.fasttree.tree, .bac120.sm.fasttree_2023-11-24-15-5.log, .bac120.concatenation.fas are hiiden in filemanager.

After all script runs properly.

**Comment by zdf1987** [comment]
Output files *.tree, *.log and *.concatenation.fas are hidden on linux because when script writes its to disk it add dot . at start in name of each file. For example output files are:

.bac120.supermatrix.fasttree.tree, .bac120.sm.fasttree_2023-11-24-15-5.log, .bac120.concatenation.fas are hiiden in filemanager.


For a properly completed run, these files will be created with names starting with prefix of the proteome folder, rather than starting with ".". I will record it and watch on whether is it a bug in other situations.


I find you are very experienced and skilled. Thank you again for your messages.


Yours,

Dao-Feng Zhang, Ph. D. 
Institute of Marine Biology, College of Oceanography, Hohai University
No.1 Xikang Road, Nanjing 210098, P.R. China.
E-mail: @hhu.edu.cn & ***@***.***
Tel：+86 15221393487

 
﻿﻿﻿﻿






---- Replied Message ----
| From | Andrew ***@***.***> |
| Date | 11/24/2023 15:20 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [zdf1987/EasyCGTree4] Execution of EasyCGTree.pl aborted due to compilation errors (Issue #3) |

update:
I replaced new tree_app-options.txt with previous version and it seems to help.
here is one line difference between them
FastTree Command-line=FastTreeMP
and
FastTree Command-line=FastTree.exe

And another tip:
Output files *.tree, *.log and *.concatenation.fas are hidden on linux because when script writes its to disk it add dot . at start in name of each file. For example output files are:
.bac120.supermatrix.fasttree.tree, .bac120.sm.fasttree_2023-11-24-15-5.log, .bac120.concatenation.fas are hiiden in filemanager.

After all script runs properly.

**Comment by zdf1987** [comment]
Please note that "tree_app-options.txt" in previous version dose not contain commend of ASTRAL, which is used for supertree approach. I will update this file as soon as possible. If you may used the supertree approach, please download the updated package tommoraw.

**Comment by Krasnopeev** [comment]
@zdf1987 thaks for replay!
I was glad to help with it!
